language: node__js
node__js:
  - "lts/*"
cache:
  directories:
    - node_modules

install:
#  - yarn install
  - npm install
script:
  # yarn
  - npm test
  - CI=false npm run build
  # sonar
  - sonar-scanner

branches:
  only:
    - main
    - dev

deploy:
  provider: heroku
  app: bnbexplorer-frontend
  api_key:
    secure: "SeOVwovR2ynId7+iGeBFlXstYtQ540A87+nlkAgja3lxNfY0ox7cthm8QsePSr3VPnXWqDFJD15aMpCf1+7hpsqtSZKFOnDk73qE6do6QalNOV6R1AD373DUpwjC7DKXi7xULNaNTG6nEUmqhTakDzWJNCuZXuezdbnomRVXkdynHTEo7C8kZmaSRARpIAuHpg638h7bnK1u4F/SLXvfitETj+PzLvq+sW9vU1xBla1slLC0729ChW0S9fFSVtV0ZUdU5h9HR2oFS/a8q3x0rcDU4X3QoiDeylEDW728FZbzh3ydDTzUSlBuNuFcFgjNI4z7naavj+m60HZTuU6AqPCERR9pDp66tYIEKVvP9U8lR8WdmRBqc+QG3x2vV0LDW4g8sMhMz2Tsgvk67cKb41/zEDnfZATeP8XvduMGKEHRRvl2TCbpCJmei+gZ0znD1Z0YwTRPyJNZfZfGlp+gdbroR44jr3hUnwsgGAhfI/w06w9nJl6L7lYaQAQ386X7HU4GmuN8Utr8AJwyL/3pgRhiST8q4KxQFE9YOyqt+BYdgtz3LEu10MrhCU4vnau4blmqx4g7UzDB8l8InS8X6P/8h2TiDwW5oR1v+xwwLSs+9Bb8oExjWNJggZG8ZVjMQNqbI1FHT3PiOIvZGofTMppGvWgQ01EOopzemhqeuHo="
  on:
    branch: main

addons:
  sonarcloud:
    organization: "uzhase-fs21"
    token:
      secure: qCJiDQVBRpcADrPWIQFX2HL+hjMA6HR5WdO8YiiHwf4uDCcEFwbHRNfEik4RZmArEiam7XvNn73IWp6Imw5SP8ZKnFswE4jX7TL7CaCUnHEZoNZs/YIBCinnjHl+uDMVA2aC7rDuxVwg576Z8DHTFyXwkcenapKCcKjrBobEd8Mk8nPTqWC5XAQDWUMpNXdP9y/znXh2w0ps/wLzL5PvAslEYS5LKGlmnbeX53SKk53CnQsK700pVN8nAML+MxBDa2EC0Ztw1CZmLFqAgMxTl7XDkl0cFOhGkWiOXgFSq56oMCBThlWSpE+oW6OHILm23ztvXoVS2B2YqLxII8HDOt7ymxkRWMf3ee8TMa58gM6DL/AXE2E4IayhufIVMCGeLZO2sSpFBkahm0Cl/2hKbFrM541NqgZkWxdJvvTYkHMd4vD4jBCLbhUERkMaOBy9w3d2yVRQ/uZqLQhEgQ/lu8MMzNuY1S1feTdau4TPWGHoIowHNfO6XHZyoMY0FLpnlinMAvU2nxdZFamHwpk/FrO3+j4cNE9EJAHcdJW82ugrCc9pqYBH4xuaXF4p30KIoXKb5xXjeqjgSyfKi/yViboO5LgbyiZcGCpwAFYbzYuXK0C/0CYlGSNt5RzJ1gDb9q38Y1pwI/zhOiHAQ6ycuF+SeFlH6V4j5FBNEkDPjSc=

notifications:
  email: false

env:
  global:
    secure: SONAR_TOKEN=qCJiDQVBRpcADrPWIQFX2HL+hjMA6HR5WdO8YiiHwf4uDCcEFwbHRNfEik4RZmArEiam7XvNn73IWp6Imw5SP8ZKnFswE4jX7TL7CaCUnHEZoNZs/YIBCinnjHl+uDMVA2aC7rDuxVwg576Z8DHTFyXwkcenapKCcKjrBobEd8Mk8nPTqWC5XAQDWUMpNXdP9y/znXh2w0ps/wLzL5PvAslEYS5LKGlmnbeX53SKk53CnQsK700pVN8nAML+MxBDa2EC0Ztw1CZmLFqAgMxTl7XDkl0cFOhGkWiOXgFSq56oMCBThlWSpE+oW6OHILm23ztvXoVS2B2YqLxII8HDOt7ymxkRWMf3ee8TMa58gM6DL/AXE2E4IayhufIVMCGeLZO2sSpFBkahm0Cl/2hKbFrM541NqgZkWxdJvvTYkHMd4vD4jBCLbhUERkMaOBy9w3d2yVRQ/uZqLQhEgQ/lu8MMzNuY1S1feTdau4TPWGHoIowHNfO6XHZyoMY0FLpnlinMAvU2nxdZFamHwpk/FrO3+j4cNE9EJAHcdJW82ugrCc9pqYBH4xuaXF4p30KIoXKb5xXjeqjgSyfKi/yViboO5LgbyiZcGCpwAFYbzYuXK0C/0CYlGSNt5RzJ1gDb9q38Y1pwI/zhOiHAQ6ycuF+SeFlH6V4j5FBNEkDPjSc=
