name: GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies
        run: |
            sudo npm i
            sudo npm i -g parcel-bundler
          
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/node_modules
      
      - name: Build
        uses: fabiank0/jsdoc-action@master
        with:
          source_dir: ./src
          output_dir: ./docs
          template: better-docs
          config_file: jsdoc.conf.json
          front_page: README.md
        
      - name: List files in the repository2
        run: |
          ls ${{ github.workspace }}
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
