name: GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install Dependencies
        run: |
            sudo npm i
            sudo npm i -g parcel-bundler
          
      - name: build docs
        run: sudo npm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs2
