name: GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Dependencies
        run: |
              sudo npm i 
              sudo npm i -g react
              sudo npm i -g parcel-bundler
              sudo npm i -g better-docs
              sudo npm i -g react-dom
        
      - name: Build
        uses: brunokrauss/jsdoc-action@1
        with:
            jsdoc-path: 'src'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
